### ISSUE TITLE
desktop version

### ISSUE THREAD

**Issue by Alexoid1** [elmejdki/sixpack-tracker-frontend#2]
First of all congrats!!
Using your app in desktop computer I can see that the height of the components take all the screen and that doesn't look good.

**Comment by elmejdki** [comment]
Hi, @Alexoid1 

Thanks for your notice I know that to be honest, and I'm planning to make it friendly to computers too in the future, but this app was built first only for mobile phone please try to use your phone on the app to have a better user experience, tell I made the necessary changes to support desktop views.

Regards,
Zakariae.
